// AUTO-GENERATED by @clamator/codegen v0.1.0 from arith.ts.
// DO NOT EDIT. Re-run codegen to update.
import { arithContract } from '@/contracts/arith';
import type { ClamatorClient } from '@clamator/protocol';
import type { z } from 'zod';

export type AddParams = z.infer<typeof arithContract.methods.add.params>;
export type AddResult = z.infer<typeof arithContract.methods.add.result>;
export type DivideParams = z.infer<typeof arithContract.methods.divide.params>;
export type DivideResult = z.infer<typeof arithContract.methods.divide.result>;

export class ArithClient {
  constructor(private client: ClamatorClient) {}
  add(params: AddParams): Promise<AddResult> {
    return this.client.call('arith', 'add', params);
  }
  divide(params: DivideParams): Promise<DivideResult> {
    return this.client.call('arith', 'divide', params);
  }
}

export interface ArithService {
  add(params: AddParams): Promise<AddResult>;
  divide(params: DivideParams): Promise<DivideResult>;
}
