// AUTO-GENERATED by @clamator/codegen v0.1.7 from launch.ts.
// DO NOT EDIT. Re-run codegen to update.
import { launchContract } from './launch.js';
import type { ClamatorClient } from '@clamator/protocol';
import type { z } from 'zod';

export type StartParams = z.infer<typeof launchContract.methods.start.params>;
export type StartResult = z.infer<typeof launchContract.methods.start.result>;

export class LaunchClient {
  constructor(private client: ClamatorClient) {}
  start(params: StartParams, opts?: { timeoutMs?: number }): Promise<StartResult> {
    return this.client.call('launch', 'start', params, opts);
  }
}

export interface LaunchService {
  start(params: StartParams, opts?: { timeoutMs?: number }): Promise<StartResult>;
}
