# AUTO-GENERATED by @clamator/codegen v0.1.0 from arith.ts.
# DO NOT EDIT. Re-run codegen to update.
from __future__ import annotations
from abc import ABC, abstractmethod
from clamator_protocol import ClamatorClient, Contract, MethodEntry

from pydantic import BaseModel, ConfigDict


class AddParams(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    a: int
    b: int


class AddResult(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    sum: int


class DivideParams(AddParams):
    pass


class DivideResult(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    q: float
    r: int


class ArithClient:
    def __init__(self, client: ClamatorClient) -> None:
        self._client = client

    async def add(self, params: AddParams, *, timeout_ms: int | None = None) -> AddResult:
        raw = await self._client.call("arith", "add", params.model_dump(mode='json', by_alias=True), timeout_ms=timeout_ms)
        return AddResult.model_validate(raw)

    async def divide(self, params: DivideParams, *, timeout_ms: int | None = None) -> DivideResult:
        raw = await self._client.call("arith", "divide", params.model_dump(mode='json', by_alias=True), timeout_ms=timeout_ms)
        return DivideResult.model_validate(raw)


class ArithService(ABC):
    @abstractmethod
    async def add(self, params: AddParams) -> AddResult: ...

    @abstractmethod
    async def divide(self, params: DivideParams) -> DivideResult: ...


METHODS = {
    "add": MethodEntry(params_model=AddParams, result_model=AddResult, handler_attr="add"),
    "divide": MethodEntry(params_model=DivideParams, result_model=DivideResult, handler_attr="divide"),
}

arith_contract = Contract(
    service="arith",
    methods=METHODS,
)
