# AUTO-GENERATED by @clamator/codegen v0.1.7 from launch.ts.
# DO NOT EDIT. Re-run codegen to update.
from __future__ import annotations
from abc import ABC, abstractmethod
from clamator_protocol import ClamatorClient, Contract, MethodEntry

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel


class StartParams(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    process_id: str = Field(..., alias="processId")


class StartResult1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ok: Literal[True]
    run_id: str = Field(..., alias="runId")


class StartResult2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ok: Literal[False]
    reason: Literal["not-launchable", "already-running", "not-found"]


class StartResult(RootModel[StartResult1 | StartResult2]):
    root: StartResult1 | StartResult2


class LaunchClient:
    def __init__(self, client: ClamatorClient) -> None:
        self._client = client

    async def start(self, params: StartParams, *, timeout_ms: int | None = None) -> StartResult:
        raw = await self._client.call("launch", "start", params.model_dump(mode='json', by_alias=True), timeout_ms=timeout_ms)
        return StartResult.model_validate(raw)


class LaunchService(ABC):
    @abstractmethod
    async def start(self, params: StartParams) -> StartResult: ...


METHODS = {
    "start": MethodEntry(params_model=StartParams, result_model=StartResult, handler_attr="start"),
}

launch_contract = Contract(
    service="launch",
    methods=METHODS,
)
