# AUTO-GENERATED by @clamator/codegen v0.1.0 from notifications.ts.
# DO NOT EDIT. Re-run codegen to update.
from __future__ import annotations
from abc import ABC, abstractmethod
from clamator_protocol import ClamatorClient, Contract, MethodEntry

from pydantic import BaseModel, ConfigDict


class PingParams(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    tag: str | None = None

class NotificationsClient:
    def __init__(self, client: ClamatorClient) -> None:
        self._client = client

    async def ping(self, params: PingParams) -> None:
        await self._client.notify("notifications", "ping", params.model_dump(by_alias=True))


class NotificationsService(ABC):
    @abstractmethod
    async def ping(self, params: PingParams) -> None: ...


METHODS = {
    "ping": MethodEntry(params_model=PingParams, result_model=None, handler_attr="ping"),
}

notifications_contract = Contract(
    service="notifications",
    methods=METHODS,
)
