import path from 'node:path';
import fs from 'node:fs/promises';
import { spawn } from 'node:child_process';
import type { IrContract } from './ir.js';
import { camelToSnake, kebabAndCamelToPascal } from './case.js';
import { VERSION } from './version.js';

export interface EmitPyOptions {
  outDir: string;
  /** Path to `datamodel-codegen` CLI; defaults to "datamodel-codegen". */
  datamodelCodegenBin?: string;
}

/** datamodel-codegen invocation result captured for tests. */
export interface PyEmitResult {
  filesWritten: string[];
}

export async function emitPy(contracts: IrContract[], opts: EmitPyOptions): Promise<PyEmitResult> {
  await fs.mkdir(opts.outDir, { recursive: true });
  const filesWritten: string[] = [];
  const bin = opts.datamodelCodegenBin ?? 'datamodel-codegen';

  for (const c of contracts) {
    // Combine all params/result schemas into one root JSON Schema with $defs, then run datamodel-codegen.
    const defs: Record<string, unknown> = {};
    const ordered: { defName: string; modelName: string }[] = [];
    for (const m of c.methods) {
      const N = upperFirst(m.name);
      defs[`${N}Params`] = m.params.jsonSchema;
      ordered.push({ defName: `${N}Params`, modelName: `${N}Params` });
      if (m.result) {
        defs[`${N}Result`] = m.result.jsonSchema;
        ordered.push({ defName: `${N}Result`, modelName: `${N}Result` });
      }
    }
    const wrapper = {
      $schema: 'http://json-schema.org/draft-07/schema#',
      type: 'object',
      $defs: defs,
    };
    // Write a temp wrapper schema file.
    const tmp = await fs.mkdtemp(path.join(opts.outDir, '.tmp-'));
    const schemaPath = path.join(tmp, 'schema.json');
    await fs.writeFile(schemaPath, JSON.stringify(wrapper, null, 2));
    const modelsPath = path.join(tmp, 'models.py');
    await runDatamodelCodegen(bin, schemaPath, modelsPath);
    let modelsBody = await fs.readFile(modelsPath, 'utf-8');
    // Strip datamodel-codegen header (comment block + from __future__ imports)
    // to avoid duplicates with our own header.
    modelsBody = modelsBody
      .replace(/^(#[^\n]*\n)*/m, '')            // leading comment lines
      .replace(/^from __future__[^\n]*\n/gm, '') // __future__ imports (already in our header)
      .trim();
    await fs.rm(tmp, { recursive: true });

    const tail = renderPyTail(c);
    // Note: pydantic imports come from modelsBody (datamodel-codegen output);
    // we only add imports that modelsBody won't provide.
    const header = `# AUTO-GENERATED by @clamator/codegen v${VERSION} from ${path.basename(c.sourceFile)}.
# DO NOT EDIT. Re-run codegen to update.
from __future__ import annotations
from abc import ABC, abstractmethod
from clamator_protocol import ClamatorClient, Contract, MethodEntry

`;
    const file = path.join(opts.outDir, `${c.service}.py`);
    // Three newlines between the (trimmed) Pydantic models block and the tail
    // (which starts with `class <Service>Client:`) produce two blank lines —
    // PEP-8's required spacing before top-level class definitions.
    await fs.writeFile(file, header + modelsBody + '\n\n\n' + tail, 'utf-8');
    filesWritten.push(file);
  }
  return { filesWritten };
}

function runDatamodelCodegen(bin: string, schemaPath: string, outPath: string): Promise<void> {
  return new Promise((resolve, reject) => {
    const args = [
      '--input', schemaPath,
      '--input-file-type', 'jsonschema',
      '--output', outPath,
      '--output-model-type', 'pydantic_v2.BaseModel',
      '--target-python-version', '3.11',
      '--field-constraints',
      '--use-double-quotes',
      '--snake-case-field',
      '--enum-field-as-literal', 'all',
      '--reuse-model',
      '--skip-root-model',
    ];
    const child = spawn(bin, args, { stdio: ['ignore', 'pipe', 'pipe'] });
    let stderr = '';
    child.stderr.on('data', chunk => { stderr += chunk.toString(); });
    child.on('error', reject);
    child.on('exit', code => {
      if (code === 0) resolve();
      else reject(new Error(`datamodel-codegen exited ${code}: ${stderr}`));
    });
  });
}

function upperFirst(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

function renderPyTail(c: IrContract): string {
  const Pascal = kebabAndCamelToPascal(c.service);

  const clientLines = c.methods.map(m => {
    const N = upperFirst(m.name);
    const snake = camelToSnake(m.name);
    if (m.isNotification) {
      return `    async def ${snake}(self, params: ${N}Params) -> None:
        await self._client.notify("${c.service}", "${m.name}", params.model_dump(by_alias=True))`;
    }
    return `    async def ${snake}(self, params: ${N}Params) -> ${N}Result:
        raw = await self._client.call("${c.service}", "${m.name}", params.model_dump(by_alias=True))
        return ${N}Result.model_validate(raw)`;
  }).join('\n\n');

  const abcLines = c.methods.map(m => {
    const N = upperFirst(m.name);
    const snake = camelToSnake(m.name);
    if (m.isNotification) {
      return `    @abstractmethod\n    async def ${snake}(self, params: ${N}Params) -> None: ...`;
    }
    return `    @abstractmethod\n    async def ${snake}(self, params: ${N}Params) -> ${N}Result: ...`;
  }).join('\n\n');

  const methodsEntries = c.methods.map(m => {
    const N = upperFirst(m.name);
    const snake = camelToSnake(m.name);
    const result = m.isNotification ? 'None' : `${N}Result`;
    return `    "${m.name}": MethodEntry(params_model=${N}Params, result_model=${result}, handler_attr="${snake}"),`;
  }).join('\n');

  const serviceVar = camelToSnake(c.service.replace(/-/g, '_')) + '_contract';

  return `class ${Pascal}Client:
    def __init__(self, client: ClamatorClient) -> None:
        self._client = client

${clientLines}


class ${Pascal}Service(ABC):
${abcLines}


METHODS = {
${methodsEntries}
}

${serviceVar} = Contract(
    service="${c.service}",
    methods=METHODS,
)
`;
}
