import path from 'node:path';
import fs from 'node:fs/promises';
import type { IrContract } from './ir.js';
import { kebabAndCamelToPascal } from './case.js';
import { VERSION } from './version.js';

export interface EmitTsOptions {
  outDir: string;
  contractImportPath: string;  // how the generated file imports the source contract object
}

export async function emitTs(contracts: IrContract[], opts: EmitTsOptions): Promise<string[]> {
  await fs.mkdir(opts.outDir, { recursive: true });
  const written: string[] = [];
  for (const c of contracts) {
    const file = path.join(opts.outDir, `${c.service}.ts`);
    await fs.writeFile(file, renderTsFile(c, opts), 'utf-8');
    written.push(file);
  }
  return written;
}

function renderTsFile(c: IrContract, opts: EmitTsOptions): string {
  const Pascal = kebabAndCamelToPascal(c.service);
  const sourceBase = path.basename(c.sourceFile);
  const exportName = `${c.service.replace(/-([a-z])/g, (_, ch) => ch.toUpperCase())}Contract`;

  const typeAliases = c.methods.map(m => {
    const N = upperFirst(m.name);
    const params = `export type ${N}Params = z.infer<typeof ${exportName}.methods.${m.name}.params>;`;
    if (m.isNotification) return params;
    return `${params}\nexport type ${N}Result = z.infer<typeof ${exportName}.methods.${m.name}.result>;`;
  }).join('\n');

  const clientMethods = c.methods.map(m => {
    const N = upperFirst(m.name);
    if (m.isNotification) {
      return `  ${m.name}(params: ${N}Params): Promise<void> {\n    return this.client.notify('${c.service}', '${m.name}', params);\n  }`;
    }
    return `  ${m.name}(params: ${N}Params): Promise<${N}Result> {\n    return this.client.call('${c.service}', '${m.name}', params);\n  }`;
  }).join('\n');

  const serviceMethods = c.methods.map(m => {
    const N = upperFirst(m.name);
    if (m.isNotification) return `  ${m.name}(params: ${N}Params): Promise<void>;`;
    return `  ${m.name}(params: ${N}Params): Promise<${N}Result>;`;
  }).join('\n');

  const importPath = opts.contractImportPath.replace(/\{service\}/g, c.service);
  return `// AUTO-GENERATED by @clamator/codegen v${VERSION} from ${sourceBase}.
// DO NOT EDIT. Re-run codegen to update.
import { ${exportName} } from '${importPath}';
import type { ClamatorClient } from '@clamator/protocol';
import type { z } from 'zod';

${typeAliases}

export class ${Pascal}Client {
  constructor(private client: ClamatorClient) {}
${clientMethods}
}

export interface ${Pascal}Service {
${serviceMethods}
}
`;
}

function upperFirst(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}
